config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todos
  resources :tasks
  # Defining root
  root 'home#index'

  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user

  def progress
    return 0 if tasks.empty?

    completed_tasks = tasks.where(done: true).count
    total_tasks = tasks.count

    (completed_tasks.to_f / total_tasks * 100).round(2)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_todos

  private

  def set_todos
    @todos = Todo.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @task = Task.create(task_params)

    if @task.save
      redirect_to todo_path(@task.todo_id)
    else
      redirect_to root_path
    end
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to todo_path(@task.todo_id)
    else
      redirect_to root_path
    end
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      redirect_to todo_path(@task.todo_id), notice: 'Tarefa excluída.'
    else
      redirect_to todo_path(@task.todo_id), alert: 'Tarefa não pôde ser excluída.'
    end
  end


  private

  def task_params
    params.require(:task).permit(:title, :done, :todo_id)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
    @task = Task.new
    @tasks = @todo.tasks
    @progress = @todo.progress
  end

  # GET /todos/new
  def new
    #@todo = Todo.new
    @todo = current_user.todos.build
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    #@todo = Todo.new(todo_params)
    @todo = current_user.todos.build(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo list criada." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo alterada com sucesso." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy!

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @todo = current_user.todos.find_by(id: params[:id])
    redirect_to todos_path, notice: "Não Autorizado" if @todo.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/" style="margin-left: 3rem; font-size: 30px">
    <%= image_tag 'logo2.png', style: 'width: 30px;', alt: '...' %>
    To do 360</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">To do 360</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active mb-2" aria-current="page" href="/">Home</a>
          </li>

          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "To-dos", todos_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Editar Perfil", edit_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item mb-2">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Listas
              </a>
              <ul class="dropdown-menu dropdown-menu-dark">
                <% if @todos.present? %>
                  <% @todos.each do |t| %>
                    <% if t.user_id == current_user.id %>
                      <li>
                        <%= link_to t.name, todo_path(t),  class: "dropdown-item" %>
                      </li>
                    <% end %>
                  <% end %>
                <% end %>
              </ul>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="d-flex justify-content-center align-items-center" style="min-height: 70vh;">
  <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel" style="max-width: 888px;">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag 'intro_1.png', class: 'd-block w-100', alt: '...' %>
        <div class="carousel-caption d-none d-md-block">
          <h5>To do 360!</h5>
          <p>Muito bem-vindo(a/e) ao seu app de organização!</p>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag 'intro_2.png', class: 'd-block w-100', alt: '...' %>
        <div class="carousel-caption d-none d-md-block">
          <h5>To do 360!</h5>
          <p>Construa seu planejamento de forma simples e prática</p>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag 'intro_3.png', class: 'd-block w-100', alt: '...' %>
        <div class="carousel-caption d-none d-md-block">
          <h5>To do 360!</h5>
          <p><a class="link-dark link-offset-2 link-underline link-underline-opacity-0 link-underline-opacity-100-hover" href="/todos">Comece agora mesmo!</a></p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

<div class="d-flex p-2 justify-content-center">
  <a class="btn btn-dark btn-lg" href="/todos" role="button">Criar Lista</a>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt">
  <head>
    <%= favicon_link_tag asset_path('favicon-16x16.png')%>
    <title>To Do 360</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <%= render 'home/header' %>

    </br>
    </br>
    </br>
    </br>


    <section style="display: flex; justify-content: center; align-items: center; padding-bottom: 60px;">
      <div style="width: 80%;">
        <% if notice %>
          <%= render 'layouts/alerts' %>
        <% end %>
        <%= yield %>
      </div>
    </section>

  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: local_assigns[:model] || todo) do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-floating mb-3">
    <%= form.text_field :name, class: 'form-control', id: 'todo_name', placeholder: 'Enter todo name' %>
    <%= form.label :name, 'Nome', for: 'todo_name' %>
    <%= form.number_field :user_id, id: :todo_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>

  <div class="d-flex w-100 justify-content-center">
    <%= form.submit local_assigns[:button_text] || 'Submit', class: "btn btn-success" %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div class="d-flex justify-content-center mb-5" id="<%= dom_id todo %>">
  <h3>
    <strong>Lista:</strong>
    <%= todo.name %>
  </h3>

</div>

app/views/todos/_todo_card.html.erb
<div class="card mb-3">
  <div class="card-header">
    Criado em: <%= todo.created_at.strftime("%d/%m/%Y") %>  </div>
  <div class="card-body">
    <h5 class="card-title"><%= todo.name %></h5>
    <div class="progress mb-4 mt-4" role="progressbar" aria-label="Animated striped example" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
      <div class="progress-bar" role="progressbar" style="width: <%= todo.progress %>%" aria-valuenow="<%= todo.progress %>" aria-valuemin="0" aria-valuemax="100"><b><%= todo.progress %>%</b></div>
    </div>
    <div class="d-flex">
      <%= link_to "Mostrar To-do", todo, class: "btn btn-dark", style: "margin-right: 10px" %>
      <%= button_to todo_path(todo), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
        Excluir
      <% end %>
    </div>
  </div>
</div>

app/views/todos/edit.html.erb
</br>
</br>

<h1 style="text-align: center; margin-bottom: 20px;">Editar Lista</h1>

<%= render "form", todo: @todo, button_text: "Salvar" %>

<br>

<div class="d-flex justify-content-center mt-5" style="gap: 20px;">
  <%= link_to "Mostrar Lista", @todo, class: "btn btn-outline-primary" %>
  <%= link_to "Voltar", todos_path, class: "btn btn-outline-dark" %>
</div>

app/views/todos/index.html.erb
<div class="d-flex align-items-center flex-column mb-5">
  <h1>To do Lists</h1>
  <h6> gerencie suas listas! </h6>
</div>


<div class="mb-4" id="todos">
  <% if @todos.present? && current_user.present? %>
    <% @todos.each do |todo| %>
      <% if todo.user_id == current_user.id %>
        <%= render partial: 'todo_card', locals: { todo: todo } %>
      <% end %>
    <% end %>
  <% end %>

</div>

<div class="d-flex justify-content-center">
  <%= link_to "Nova Lista", new_todo_path, class: "btn btn-success" %>
</div>

app/views/todos/new.html.erb
<div class="d-flex align-items-center mb-5 flex-column">
  <h1>Nova Lista</h1>
  <h6> crie sua lista de tarefas! </h6>
</div>

<%= render "form", todo: @todo, button_text: "Criar" %>

<br>

app/views/todos/show.html.erb
<%= render @todo %>

<ul class="list-group mb-5">
  <% @tasks.each do |task| %>
    <li class="list-group-item d-flex justify-content-between align-items-center">

      <% if task.done == true %>

        <label class="form-check-label", style="margin-right: auto", for="firstCheckboxStretched"><strike><%= task.title %></strike></label>

        <%= form_for task do |f| %>
          <%= f.hidden_field :done, :value => false %>
          <%= f.submit "Não Realizado", class: "btn btn-warning" %>
        <% end %>

      <% elsif task.done == false %>

        <label class="form-check-label", style="margin-right: auto;" for="firstCheckboxStretched"><%= task.title %></label>

        <%= form_for task do |f| %>
          <%= f.hidden_field :done, :value => true %>
          <%= f.submit "Realizado", class: "btn btn-success" %>
        <% end %>

      <% end %>
      <%= button_to "Excluir", task_path(task), method: :delete, class: "btn btn-danger", style: "margin-left: 10px;" %>
    </li>
  <% end %>
</ul>

<h3 style="text-align: center"> Adicionar Tarefa </h3>

<section class="d-flex flex-column align-items-center">
  <%= form_for @task, html: { class: "w-100" } do |f| %>

    <div class="form-floating mb-3">
      <%= f.text_field :title, class: 'form-control', id: 'task_title', placeholder: 'Enter task title' %>
      <%= f.label :title, 'Tarefa', for: 'task_title' %>
    </div>

    <%= f.hidden_field :done, value: false %>
    <%= f.hidden_field :todo_id, value: @todo.id %>

    <div class="d-flex justify-content-center w-100">
      <%= f.submit "Adicionar", class: "btn btn-success" %>
    </div>

  <% end %>

  <div class="d-flex mt-5 w-100 justify-content-between" style="gap: 20px;">
    <div>
      <%= link_to "Editar", edit_todo_path(@todo), class: "btn btn-outline-primary" %>
      <%= link_to "Voltar", todos_path, class: "btn btn-outline-dark" %>
    </div>
    <div>
      <%= button_to "Excluir Lista", @todo, method: :delete, form: { class: "d-inline" }, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
    </div>
  </div>
</section>